services:
  s3mock:
    image: adobe/s3mock:latest
    environment:
      - debug=true
      - retainFilesOnExit=true
      - root=containers3root
    ports:
      - 9090:9090
      - 9191:9191
    volumes:
      - ../../locals3root:/containers3root
    networks:
      - default

networks:
  default:
    external: true
    name: ${APP_NAME:-CodeHorizon}_${APP_ENV_NAME:-sbx00}_network
