services:
  streamlit:
    build:
      context: ./streamlit
      args:
        REGISTRY: ${REGISTRY:-}
    expose:
      - "8501"
    environment:
      - FASTAPI_URL=http://fastapi:8000
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - fastapi
      - redis
      - jaeger
    networks:
      - default

  fastapi:
    build:
      context: ./fastapi
      args:
        REGISTRY: ${REGISTRY:-}
    expose:
      - "8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - redis
      - jaeger
    networks:
      - default

  redis:
    image: ${REGISTRY:-}redis:6
    expose:
      - "6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - default

  s3_worker:
    build:
      context: ./python_workers
      dockerfile: s3_worker/Dockerfile
      args:
        REGISTRY: ${REGISTRY:-}
    environment:
      - REDIS_URL=redis://redis:6379
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - redis
      - jaeger
    networks:
      - default

  easynet_worker:
    build:
      context: ./python_workers
      dockerfile: easynet_worker/Dockerfile
      args:
        REGISTRY: ${REGISTRY:-}
    environment:
      - REDIS_URL=redis://redis:6379
      # - ENVIRONMENT=${ENVIRONMENT:-local}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    depends_on:
      - redis
      - jaeger
    networks:
      - default

  jaeger:
    image: ${REGISTRY:-}jaegertracing/all-in-one:latest
    expose:
      - "16686"  # Jaeger UI
      - "6831/udp"  # Jaeger agent
      - "4317"   # OTLP gRPC
      - "4318"   # OTLP HTTP
    networks:
      - default

  nginx_reverse_proxy:
    build:
      context: ./nginx_reverse_proxy
      args:
        REGISTRY: ${REGISTRY:-}
    ports:
      - "${NGINX_PUBLIC_PORT:-8080}:80"
    volumes:
      - ./docs:/usr/share/nginx/html:ro
    depends_on:
      - mkdocs
      - streamlit
    networks:
      - default

  mkdocs:
    build:
      context: ./mkdocs
      args:
        REGISTRY: ${REGISTRY:-}
    volumes:
      - ./mkdocs:/docs
      - ./docs:/output
    networks:
      - default
  
networks:
  default:
    external: true
    name: ${APP_NAME:-CodeHorizon}_${APP_ENV_NAME:-sbx00}_network