[theme]
base = "light"
primaryColor="#00915a"
backgroundColor="#000000"
secondaryBackgroundColor="#00915a"
textColor="#ffffff"
font = "sans serif"
accentColor = "#8fd429"

[server]
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
