[server]
enableCORS = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
showErrorDetails = true
