site_name: Project Documentation
theme:
  name: material
  features:
    - content.code.annotate
docs_dir: doc_files
site_dir: /output
nav:
  - Home: index.md
  - About: about.md
  - Architecture: architecture.md
  - Development workflow: development_workflow.md
  - Development workflow v2: development_workflow_v2.md
  - Views Logic:
    - Compliance Status:
      - Backup Status: views_logic/compliance_status/backup_status.md
      - Operational Status: views_logic/compliance_status/operational_status.md
      - Validation Status: views_logic/compliance_status/validation_status.md
    - Remote Access Status:
      - Page 1: views_logic/remote_access/page1.md
      - Page 2: views_logic/remote_access/page2.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format